### ISSUE TITLE
System.exit - это очень, очень плохо

### ISSUE THREAD

**Issue by AlphaBeth** [Michaelsladkov/programming-lab7#1]
https://github.com/Michaelsladkov/programming-lab7/blob/7da9b48faca20f7d3696c26c58bb6d5080701a20/server/src/main/java/util/database/DatabaseConnector.java#L19

Становится слишком тяжело отследить, почему ваша программа вдруг остановилась

**Comment by Michaelsladkov** [comment]
Теперь дайджест создаётся в конструкторе, а ошибка обрабатывается в Main без System.exit
