### ISSUE TITLE
Общее состояние меняется из нескольких потоков

### ISSUE THREAD

**Issue by AlphaBeth** [Michaelsladkov/programming-lab7#3]
https://github.com/Michaelsladkov/programming-lab7/blob/7da9b48faca20f7d3696c26c58bb6d5080701a20/server/src/main/java/command/Invoker.java#L85-L93

Как я вижу, в программе есть один общий объект Invoker. У него поле commandHashMap, в нём изменяемые объекты команд. В этоге несколько потоков меняют общие объекты.

**Comment by Michaelsladkov** [comment]
Теперь в каждом потоке создаётся своя таблица команд
